---
title: "Data donation"
---

## What is data donation?

It's a study paradigm to process and collect digital trace data contained in so called data download packages. Users of a (social media) platform obtain these packages as part of the study via the platform itself and can then "donate" them via a [software](https://github.com/d3i-infra/data-donation-task).

You can read about the software in detail [here](https://d3i-infra.github.io/data-donation-task/) and about the paradigm itself [here](https://datadonation.eu/).

## How much does it cost?

The software can run on the [SURF Research Cloud](../cloud/src.qmd) as described [here](https://d3i-infra.github.io/data-donation-task/articles/deployment.html). You can obtain credits for this by requesting an [EINFRA or small-compute grant](https://d3i-infra.github.io/data-donation-task/articles/deployment.html#instructions-to-fill-in-the-einfra-grant-form). Otherwise, get in touch or if you already have a wallet, you can use the calculator to estimate the costs - for the right estimate, use 2 CPU cores and the time you expect your study to run, usually around 2-3 months.

## How can we help?

Preparing a data donation study has two technical components:

- Creating data processing scripts (Python)
- Running the software on cloud infrastructure

If you need help with any of these or want to know more about data donation in general, reach out.

## How does it look like?

[Example project](https://paulmaxus.github.io/dd-videos/)