content:
  - name: home
    label: Home
    type: file
    path: index.qmd
    fields:
      - { name: title, label: Title, type: string, required: true }
      - name: listing
        label: Lists
        type: object
        list: true
        fields:
          - { name: id, label: id, type: string }
          - { name: contents, label: folder, type: string }
          - { name: template, label: ejs file, type: string }
      - { name: body, label: Body, type: rich-text }
components:
  email: # 'email' is the component name/key
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com).'