project:
  type: website

website:
  title: "Max Paulus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: src.qmd
        text: SRC

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center


